# Generated by Django 3.2.20 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='photolost',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
